window:

  dimensions:
    columns: 80
    lines:   24

  padding:
    x: 10
    y: 10

  dynamic_padding: false

  decorations: full

  startup_mode: Windowed

  dynamic_title: true

  opacity: 1.0

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: DejaVu Sans Mono
    style: Book

  bold:
    family: DejaVu Sans Mono
    style: Bold

  italic:
    family: DejaVu Sans Mono
    style: Oblique

  size: 12

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

colors:
  # Default colors
  primary:
    background: '0x262626'
    foreground: '0xfff1f3'

  # Normal colors
  normal:
    black:   '0x262626'
    red:     '0xfd6883'
    green:   '0xadda78'
    yellow:  '0xf9cc6c'
    blue:    '0xf38d70'
    magenta: '0xa8a9eb'
    cyan:    '0x85dacc'
    white:   '0xfff1f3'

  # Bright colors
  bright:
    black:   '0x72696a'
    red:     '0xfd6883'
    green:   '0xadda78'
    yellow:  '0xf9cc6c'
    blue:    '0xf38d70'
    magenta: '0xa8a9eb'
    cyan:    '0x85dacc'
    white:   '0xfff1f3'

  indexed_colors: []

bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xffffff'

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: false

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: false

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false
