live_config_reload = false


[colors]
draw_bold_text_with_bright_colors = true
indexed_colors = []

[colors.bright]
black = "0x72696a"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.normal]
black = "0x262626"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.primary]
background = "0x262626"
foreground = "0xfff1f3"


[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 10
y = 10


[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0


[font]
size = 12

[font.normal]
family = "DejaVu Sans Mono"
style = "Book"

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.italic]
family = "DejaVu Sans Mono"
style = "Oblique"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0


[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
# when set to true, selected text will be copied to the primary clipboard
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[cursor]
style = "Block"
unfocused_hollow = true


[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false
